title: 剑与魔法
description: Kzeroko‘s modpack site
theme: just-the-docs
color_scheme: dark

url: https://kzeroko.github.io

aux_links:
  "爱发电": "https://afdian.net/a/kzeroko"
  "QQ群聊": "https://qm.qq.com/q/WYJzKMvpyq"

aux_links_new_tab: true