title: Kzeroko
description: Kzeroko site
theme: just-the-docs

url: https://kzeroko.github.io

aux_links:
  "爱发电": "https://afdian.net/a/kzeroko"
  "爱发电2": "https://afdian.net/a/kzeroko"

aux_links_new_tab: false

color_scheme: dark